# Generated by Django 4.1.7 on 2023-02-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard')], default='E', max_length=6)),
            ],
            options={
                'ordering': ('-score', '-date'),
            },
        ),
    ]
