# Generated by Django 4.1.7 on 2023-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'E'), ('medium', 'M'), ('hard', 'H')], default='easy', max_length=6),
        ),
    ]
