# Generated by Django 4.1.7 on 2023-02-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_alter_score_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
