# Generated by Django 4.1.7 on 2023-02-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_score_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-score', '-date')},
        ),
    ]
